/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef USERAGENT_AUTODEFS_H
#define USERAGENT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_USERAGENT_NAME "UserAgent"
#define S3E_EXT_USERAGENT_HASH 0xc04a6133

#endif /* !USERAGENT_AUTODEFS_H */
